// <auto-generated />
using HappyTrees.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HappyTrees.Migrations
{
    [DbContext(typeof(PaintingContext))]
    [Migration("20191215210106_AddColorValue")]
    partial class AddColorValue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HappyTrees.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuyLink");

                    b.Property<string>("ColorName");

                    b.Property<string>("ColorValue");

                    b.Property<string>("HexColor");

                    b.Property<int>("PaintingId");

                    b.HasKey("Id");

                    b.HasIndex("PaintingId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("HappyTrees.Models.Painting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("Episode");

                    b.Property<int>("PaintingTypes");

                    b.Property<int>("Season");

                    b.Property<string>("ThumbnailFile");

                    b.Property<string>("Title");

                    b.Property<string>("VideoUrl");

                    b.HasKey("Id");

                    b.ToTable("Paintings");
                });

            modelBuilder.Entity("HappyTrees.Models.Color", b =>
                {
                    b.HasOne("HappyTrees.Models.Painting", "Painting")
                        .WithMany("Colors")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
